### ISSUE TITLE
demo for 2D in the wild images 

### ISSUE THREAD

**Issue by ghost** [facebookresearch/eft#10]
Hello, 

Can you guide on how to process in the wild images ? 

Thanks

**Comment by jhugestar** [comment]
I don't get your question. Do you mean how to process a new videos (not the sample)? If this is the question, you can just put the file path instead of the sample video path.

**Comment by ghost** [comment]
Sorry. My bad. I have edited the question.

**Comment by jhugestar** [comment]
python -m demo.demo_bodymocap --vPath ./yourpath/yourfile.mp4 

or 

 python -m demo.demo_bodymocap --vPath ./yourpath/

, where you have image files in your path

Please see the readme: https://github.com/facebookresearch/eft/blob/master/README_bodymocap.md

**Comment by ghost** [comment]
Thank you. Closing the issue.
