### ISSUE TITLE
the fine-tuned SPIN model

### ISSUE THREAD

**Issue by lyupei** [facebookresearch/eft#2]
Hi, are you willing to release the fitting code and the fine-tuned SPIN model？

**Comment by jhugestar** [comment]
Yes we plan to. We are currently cleaning up the code and may need a bit of time for the official release.

**Comment by lyupei** [comment]
Great!
Looking forward to it!

**Comment by MengXinChengXuYuan** [comment]
Hi any update to the fitting code?
