### ISSUE TITLE
COCO annto id

### ISSUE THREAD

**Issue by MengXinChengXuYuan** [facebookresearch/eft#3]
Hi thank you for sharing this great dataset first! 
But I just found that annotId doesn't match the image's name in COCO annotation provided (both all and part)
I think they should match each other? The smpl param I parsed seems do not match well either.
Or did I miss something?

The annotation from COCO:
![1](https://user-images.githubusercontent.com/19768696/90314057-75c6ff00-df43-11ea-8b7a-ce6ff2658688.png)

The annotation from eft:
![2](https://user-images.githubusercontent.com/19768696/90314067-86777500-df43-11ea-8d51-099096fa3f16.png)

The smpl param parsed by me:
![3](https://user-images.githubusercontent.com/19768696/90314074-942cfa80-df43-11ea-9908-ad0eebe56f20.png)

**Comment by MengXinChengXuYuan** [comment]
Is it possible that also provide the orignal keypnts? Or the keypnts order for multi-body in the same image may varies :(
![4](https://user-images.githubusercontent.com/19768696/90316945-64d4b880-df58-11ea-81c6-19d9772d3292.png)

**Comment by jhugestar** [comment]
To be clear, the imageName and annotation ID are not the same in COCO (e.g., you can imagine that an image may have multiple annotation IDs). The annotID we saved in EFT is the annotation ID, not "image id". The "id" in your screen shot you parsed from COCO is image ID, rather than annotation ID, I believe. Can you check this again?

You may try demo/visEFTFit_coco.py to draw bbox from COCO annotation file to verify this.

**Comment by MengXinChengXuYuan** [comment]
Ops my fault! I didn't run the demo because of some env problems! All goes well now.
Still, what about also providing the 2D keypoints? Some body reconstruction method just need 2d keypnts, and for other dataset, unlike coco which has annotation id, may have the annotation order problem?

**Comment by jhugestar** [comment]
Other datasets only have a single person in each image, so no annotation ID is necessary -- image id is the same as annotation ID. 

For the 2D keypoint, I would encourage you to download it from the original website. I believe we are not supposed to redistribute it here.

**Comment by jhugestar** [comment]
I will close this issue. Please reopen it if you have further questions.
