### ISSUE TITLE
About coco data

### ISSUE THREAD

**Issue by tszhang97** [facebookresearch/eft#5]
I have downloaded the json formats data. According to my test, the length of COCO2014-Part-ver01.json is 28,062 and that of COCO2014-All-ver01.json is 74,834. This is not consistent with the picture .Maybe there's something wrong about the name of the file.
![image](https://user-images.githubusercontent.com/39046939/91857730-e176cf00-ec9a-11ea-9635-c9d7f32b7ef7.png)

**Comment by jhugestar** [comment]
Thanks! The README was incorrect and I fixed it.
