### ISSUE TITLE
demo issue -- No module modelViewer  

### ISSUE THREAD

**Issue by ghost** [facebookresearch/eft#8]
Hello, 

While trying to run the demo there it looks for the modelViewer which isn't given. Please look into this. Thanks

**Comment by jhugestar** [comment]
Thanks for reporting this. I fixed the part. Can you retry? I guess you tried the GUI mode, right?

**Comment by ghost** [comment]
Hello. It works now. Thanks for the quick response. 
Indeed, I am using the GUI. Any chance of saving the animation as a .fbx so as to import to an 3D software (this is the an open issue #7) ?

**Comment by liangshi036** [comment]
when I try to run the demo visEFTFit.py, got  the same issue.

**Comment by jhugestar** [comment]
@xuexianju Can you open a new issue with the details because it looks like a different issue? I am gonna close this issue for now.
